version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: document_mysql_prod
    environment:
      MYSQL_ROOT_PASSWORD: your_very_strong_root_password_123!
      MYSQL_DATABASE: DocumentManagementDB
      MYSQL_USER: docuser
      MYSQL_PASSWORD: your_very_strong_password_123!
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    restart: unless-stopped
    command: --default-authentication-plugin=mysql_native_password

  api:
    build: 
      context: ./DocumentManagementAPI
      dockerfile: Dockerfile
    container_name: document_api_prod
    ports:
      - "5000:80"
    depends_on:
      - mysql
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=mysql;Database=DocumentManagementDB;User=docuser;Password=your_very_strong_password_123!;
      - JwtSettings__SecretKey=your-super-secure-production-secret-key-at-least-32-characters-long-change-this
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: document_nginx_prod
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - api
    restart: unless-stopped

volumes:
  mysql_data: