services:
  - type: web
    name: uploaddocumentbe
    env: docker
    dockerfilePath: ./DocumentManagementAPI/Dockerfile
    dockerContext: ./DocumentManagementAPI
    plan: free
    region: oregon
    branch: main
    healthCheckPath: /health
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__DefaultConnection
        value: Server=sql7.freesqldatabase.com;Database=sql7800199;User=sql7800199;Password=xa3L1w7xpG;Port=3306;SslMode=None;AllowPublicKeyRetrieval=true;ConnectionTimeout=30;
      - key: JWT_SECRET_KEY
        value: FreePlatform-SecureKey-32Chars-Min-Change-This-Production-Key-2024
      - key: JWT_ISSUER
        value: DocumentManagementAPI
      - key: JWT_AUDIENCE
        value: DocumentManagementClient
      - key: JWT_EXPIRY_MINUTES
        value: "1440"