services:
  - type: web
    name: uploaddocument
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx serve -s dist -l $PORT
    envVars:
      - key: VITE_API_BASE_URL
        value: https://uploaddocumentbe.onrender.com/api
      - key: NODE_ENV
        value: production